import { Debug } from './scenes/interfaces';

export const debugInit: Debug = {
  DevMode: false,
  DevZoom: 8,
  Level: 6, //0123456
  ModeInfinity: true,
  InfinityShots: 0,
  TimeMinutes: 7, //01234567
  MusicActive: true,
  MusicTrack: 2, // 012
  ReadySoundActive: true,
  Camera: true,
  CamerasVisible: false,
  CollidersPvP: false,
  CollidersPvAP: false,
  CollidersPvAE: false,
  CollidersAEvAE: true,
  CollidersAEvAP: true,
  CollidersABvAE: false,
  CollidersABvAP: false,
  FrictionAirActive: true,
  AEWrapScreen: false,
  WallJumpsActive: true,
  DefaultDamage: false,
  DefaultHitback: false,
  PlayerIdVisible: true,
  CharacterTinted: false,
  HealthInverted: false,
  MatricesAlways: false,
  ConsoleLogButtons: false,
  ConsoleLogConnected: false,
  UpdateLoopsNumSkip: 2, // 012
  LoadTimeExtra: true,
  AllowCharsExtended: true,
  AllowCharsChez: false,
  SlowMoExplosions: false,
  TypedLoadingText: false,
  CharOverride: false,
  CharOverrideId: 3,
  BulletsAllowGroups: true,
  BulletsFullScreen: false,
};

export const debugMax: Debug = {
  Level: 6, //0123456
  ModeInfinity: true,
  InfinityShots: 15,
  TimeMinutes: 15, //01234567
  MusicActive: true,
  MusicTrack: 2, // 012
  ReadySoundActive: true,
  Camera: true,
  CamerasVisible: false,
  CollidersPvP: false,
  CollidersPvAP: false,
  CollidersPvAE: false,
  CollidersAEvAE: true,
  CollidersAEvAP: true,
  CollidersABvAE: false,
  CollidersABvAP: false,
  FrictionAirActive: true,
  AEWrapScreen: false,
  WallJumpsActive: true,
  DefaultDamage: false,
  DefaultHitback: false,
  PlayerIdVisible: true,
  CharacterTinted: false,
  HealthInverted: false,
  MatricesAlways: false,
  ConsoleLogButtons: false,
  ConsoleLogConnected: false,
  UpdateLoopsNumSkip: 2, // 012
  LoadTimeExtra: true,
  AllowCharsExtended: true,
  AllowCharsChez: false,
  SlowMoExplosions: true,
  TypedLoadingText: false,
  DevMode: true,
  DevZoom: 10,
  CharOverride: true,
  CharOverrideId: 8,
  BulletsAllowGroups: true,
  BulletsFullScreen: true,
};
