import { Debug } from './scenes/interfaces';

export const debugInit: Debug = {
  Level: 6, //0123456
  ModeInfinity: true,
  InfinityShots: 7,
  TimeMinutes: 7, //01234567
  MusicActive: true,
  MusicTrack: 2, // 012
  ReadySoundActive: true,
  Camera: true,
  CamerasVisible: false,
  CollidersPvP: false,
  CollidersPvAP: false,
  CollidersPvAE: false,
  CollidersAEvAE: true,
  CollidersAEvAP: true,
  FrictionAirActive: true,
  AEWrapScreen: false,
  WallJumpsActive: true,
  DefaultDamage: false,
  DefaultHitback: false,
  PlayerIdVisible: true,
  CharacterTinted: false,
  HealthInverted: false,
  MatricesAlways: false,
  ConsoleLogButtons: false,
  ConsoleLogConnected: false,
  UpdateLoopsNumSkip: 2, // 012
  LoadTimeExtra: true,
  AllowCharsExtended: true,
  AllowCharsChez: false,
  SlowMoExplosions: false,
  TypedLoadingText: false,
  DevMode: false,
  DevZoom: 8,
  OverrideChar: false,
  OverrideCharId: 3,
  AllowBulletGroups: true,
  BulletsNoTime: true,
};

export const debugMax: Debug = {
  Level: 6, //0123456
  ModeInfinity: true,
  InfinityShots: 15,
  TimeMinutes: 15, //01234567
  MusicActive: true,
  MusicTrack: 2, // 012
  ReadySoundActive: true,
  Camera: true,
  CamerasVisible: false,
  CollidersPvP: false,
  CollidersPvAP: false,
  CollidersPvAE: false,
  CollidersAEvAE: true,
  CollidersAEvAP: true,
  FrictionAirActive: true,
  AEWrapScreen: false,
  WallJumpsActive: true,
  DefaultDamage: false,
  DefaultHitback: false,
  PlayerIdVisible: true,
  CharacterTinted: false,
  HealthInverted: false,
  MatricesAlways: false,
  ConsoleLogButtons: false,
  ConsoleLogConnected: false,
  UpdateLoopsNumSkip: 2, // 012
  LoadTimeExtra: true,
  AllowCharsExtended: true,
  AllowCharsChez: false,
  SlowMoExplosions: true,
  TypedLoadingText: false,
  DevMode: true,
  DevZoom: 10,
  OverrideChar: true,
  OverrideCharId: 8,
  AllowBulletGroups: true,
  BulletsNoTime: true,
};
